export const KEY_API="dc2d353b9ddadaebcdfa5c1f93065747"
export const URL_TMBD="https://api.themoviedb.org/3/"
export const LENG_TMBD="language=es-ES"
export const IMG_API="https://image.tmdb.org/t/p/w500/"
export const ADULT_API="include_adult=false"